// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6hYmcoiZAbTDkaHic14qHu8NKZ9nKONU',
    appId: '1:933672539359:web:971f82465fe1deb415c56a',
    messagingSenderId: '933672539359',
    projectId: 'hotelmanagementapp-50710',
    authDomain: 'hotelmanagementapp-50710.firebaseapp.com',
    storageBucket: 'hotelmanagementapp-50710.firebasestorage.app',
    measurementId: 'G-WM833VN701',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8-hRHMIfmuY8Dft6rj2SkY6EC_dW5ouc',
    appId: '1:933672539359:android:94466bcd351c7a3315c56a',
    messagingSenderId: '933672539359',
    projectId: 'hotelmanagementapp-50710',
    storageBucket: 'hotelmanagementapp-50710.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfQN3hW4-qG2oCGK0dVsl7mYGJQP9nGy8',
    appId: '1:933672539359:ios:953a4494996412c815c56a',
    messagingSenderId: '933672539359',
    projectId: 'hotelmanagementapp-50710',
    storageBucket: 'hotelmanagementapp-50710.firebasestorage.app',
    iosBundleId: 'com.example.hotelmanagementapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfQN3hW4-qG2oCGK0dVsl7mYGJQP9nGy8',
    appId: '1:933672539359:ios:953a4494996412c815c56a',
    messagingSenderId: '933672539359',
    projectId: 'hotelmanagementapp-50710',
    storageBucket: 'hotelmanagementapp-50710.firebasestorage.app',
    iosBundleId: 'com.example.hotelmanagementapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6hYmcoiZAbTDkaHic14qHu8NKZ9nKONU',
    appId: '1:933672539359:web:0a8009de004b351915c56a',
    messagingSenderId: '933672539359',
    projectId: 'hotelmanagementapp-50710',
    authDomain: 'hotelmanagementapp-50710.firebaseapp.com',
    storageBucket: 'hotelmanagementapp-50710.firebasestorage.app',
    measurementId: 'G-RX1440D8GS',
  );
}
